[
    {
        "Code": "V00",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "Straw",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "MISC. STRAWBERRIES",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 1,
        "ModifiedDateTime": "2021-07-05T10:43:06",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "MISC. STRAWBERRIES",
        "ReceivingCode": "V00"
    },
    {
        "Code": "V01",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "Commander",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": "0001",
        "PAStatus": false,
        "GenoType": "P48.41Q",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": "Watsonville",
        "VarietyId": 2,
        "ModifiedDateTime": "2021-02-10T06:06:12",
        "ProprietaryType": "None",
        "TradeMark": "COMMANDER",
        "Descript": "COMMANDER",
        "ReceivingCode": "V01"
    },
    {
        "Code": "V02",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "SWEDED",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "N6.3 J9",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 3,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "SWEDE",
        "ReceivingCode": "V02"
    },
    {
        "Code": "V03",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "JoeReiter",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "JOE REITER",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 4,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": "JOE REITER",
        "Descript": "JOE REITER",
        "ReceivingCode": "V03"
    },
    {
        "Code": "V04",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "OSO GRANDE",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 5,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "OSO GRANDE",
        "ReceivingCode": "V04"
    },
    {
        "Code": "V05",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "CHANDLER STRAW",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 6,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "NP",
        "TradeMark": "CHANDLER STRAW",
        "Descript": "CHANDLER STRAW",
        "ReceivingCode": "V05"
    },
    {
        "Code": "V06",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "E-26",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 7,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "E-26",
        "ReceivingCode": "V06"
    },
    {
        "Code": "V07",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "KeyLargo",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "KEY LARGO",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 8,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": "KEY LARGO",
        "Descript": "KEY LARGO",
        "ReceivingCode": "V07"
    },
    {
        "Code": "V08",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "BALBOA",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "3V23",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 9,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "BALBOA",
        "Descript": "BALBOA",
        "ReceivingCode": "V08"
    },
    {
        "Code": "V09",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "S13.116",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 10,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": "S13.116",
        "Descript": "S13.116",
        "ReceivingCode": "V09"
    },
    {
        "Code": "V10",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "UV38.401",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 11,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "UV38.401",
        "ReceivingCode": "V10"
    },
    {
        "Code": "V11",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "AVILA",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "007V258",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 12,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "AVILA",
        "ReceivingCode": "V11"
    },
    {
        "Code": "V12",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "SEASCAPE",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 13,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "SEASCAPE",
        "ReceivingCode": "V12"
    },
    {
        "Code": "V13",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "39V96",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 14,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": null,
        "Descript": "39V96",
        "ReceivingCode": "V13"
    },
    {
        "Code": "V14",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "Straw",
        "ProducingAreaCode": "0001",
        "PAStatus": false,
        "GenoType": "X13",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": "Watsonville",
        "VarietyId": 15,
        "ModifiedDateTime": "2021-07-09T17:18:24",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "X13",
        "ReceivingCode": "V14"
    },
    {
        "Code": "V14",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "Straw",
        "ProducingAreaCode": "0002",
        "PAStatus": false,
        "GenoType": "X13",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": "Salinas",
        "VarietyId": 15,
        "ModifiedDateTime": "2021-07-09T17:18:24",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "X13",
        "ReceivingCode": "V14"
    },
    {
        "Code": "V15",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "23Y267",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 16,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": null,
        "Descript": "23Y267",
        "ReceivingCode": "V15"
    },
    {
        "Code": "V16",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "Coronado",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "CORONADO",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 17,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": "CORONADO",
        "Descript": "CORONADO",
        "ReceivingCode": "V16"
    },
    {
        "Code": "V17",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "DriscollSanMiguel",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "SAN MIGUEL",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 18,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": "SAN MIGUEL",
        "Descript": "SAN MIGUEL",
        "ReceivingCode": "V17"
    },
    {
        "Code": "V18",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "19A268",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 19,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": null,
        "Descript": "19A268",
        "ReceivingCode": "V18"
    },
    {
        "Code": "V19",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "STRAW",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "20A259",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 20,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "P",
        "TradeMark": null,
        "Descript": "20A259",
        "ReceivingCode": "V19"
    },
    {
        "Code": "V1A",
        "IsProprietary": false,
        "IsActive": false,
        "PatentName": "",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 21,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "MISC. RASPBERRIES",
        "ReceivingCode": "V1A"
    },
    {
        "Code": "V1B",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "Isabel",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "G314.8",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 22,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "ISABEL",
        "ReceivingCode": "V1B"
    },
    {
        "Code": "V1C",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "HOLLINS",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "A25.3",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 23,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "HOLLINS",
        "ReceivingCode": "V1C"
    },
    {
        "Code": "V1D",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "Wilhelm",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "F175.19",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 24,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "WILHELM",
        "ReceivingCode": "V1D"
    },
    {
        "Code": "V1E",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "Sweetbriar",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "37X",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 25,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "37X-SWEETBRIAR",
        "ReceivingCode": "V1E"
    },
    {
        "Code": "V1F",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "JoeMello",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "A30.2",
        "OwnerOrg": "",
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 26,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "JOES BABY",
        "ReceivingCode": "V1F"
    },
    {
        "Code": "V1G",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "GODIVA",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "J517.1",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 27,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "GODIVA",
        "ReceivingCode": "V1G"
    },
    {
        "Code": "V1H",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "TOLA",
        "CommodityCode": "RASP",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "M48.3",
        "OwnerOrg": "",
        "Selection": "",
        "ProducingAreaName": null,
        "VarietyId": 28,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "TOLA",
        "ReceivingCode": "V1H"
    },
    {
        "Code": "V5S",
        "IsProprietary": false,
        "IsActive": true,
        "PatentName": "",
        "CommodityCode": "BLUE",
        "ProducingAreaCode": "0004",
        "PAStatus": true,
        "GenoType": "",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": "Oxnard",
        "VarietyId": 181,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "NP",
        "TradeMark": "",
        "Descript": "SOUTH MOON",
        "ReceivingCode": "V5S"
    },
    {
        "Code": "V5S",
        "IsProprietary": false,
        "IsActive": true,
        "PatentName": "",
        "CommodityCode": "BLUE",
        "ProducingAreaCode": "0020",
        "PAStatus": true,
        "GenoType": "",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": "San Quintin",
        "VarietyId": 181,
        "ModifiedDateTime": "2021-03-04T01:28:41",
        "ProprietaryType": "NP",
        "TradeMark": "",
        "Descript": "SOUTH MOON",
        "ReceivingCode": "V5S"
    },
    {
        "Code": "VZY",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "VZY",
        "CommodityCode": "Rasp",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "VZY",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 607,
        "ModifiedDateTime": "2021-07-15T16:39:02",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "VZY",
        "ReceivingCode": "VZY"
    },
    {
        "Code": "VZZ",
        "IsProprietary": true,
        "IsActive": false,
        "PatentName": "MuleTest",
        "CommodityCode": "Straw",
        "ProducingAreaCode": null,
        "PAStatus": null,
        "GenoType": "VZZ",
        "OwnerOrg": null,
        "Selection": null,
        "ProducingAreaName": null,
        "VarietyId": 606,
        "ModifiedDateTime": "2021-07-12T14:52:38",
        "ProprietaryType": "None",
        "TradeMark": "",
        "Descript": "VZZ",
        "ReceivingCode": "VZZ"
    }
]